name: news_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-152.0.dev <4.0.0'

dependencies:
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  data_connection_checker:
    git:
      url: https://github.com/chornthorn/data_connection_checker.git
      ref: master
  dotenv: ^4.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_spinkit: ^5.2.0
  get_it: ^7.6.4
  http: ^1.1.2
  intl: ^0.18.1
  lazy_load_scrollview: ^1.3.0
  lottie: ^2.7.0
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  sqflite_sqlcipher: ^2.2.1

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  analyzer: ^6.3.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/